services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /app
    image: masakinakamoto/asb-app
    platform: linux/amd64 #追加
    ports:
      - '80:8080' #追加
      - 8080:8080
      - 5050:5050
    tty: true
    volumes:
      - ./:/app
    depends_on:
      - db

  db:
    image: postgres:13.1
    container_name: db
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'dev'
    ports:
      - '5432:5432'
