spring.application.name=springboot-application

spring.datasource.driver-class-name=org.postgresql.Driver
# 使用してるSQL用の書き換え対応・最適化
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
mybatis.mapper-locations=classpath*:com/spring/springbootapplication/dao/*.xml

# 環境別設定の切り替え
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}
server.port=${PORT:8080}
